name: 'Deploy'

on:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install SAM
        uses: aws-actions/setup-sam@v2

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: SAM build
        run: sam build

      - name: SAM validate
        run: sam validate

      - name: SAM deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name "rightmove-alerter" --image-repository "110701928951.dkr.ecr.eu-west-1.amazonaws.com/samapp7427b055/lambdafunctiondfe28c74repo" --capabilities "CAPABILITY_IAM"
